version: '2'

services:
  # Web server - For live reload and development
  # This environment can be used to run npm and node
  # commands as well
  dev:
    image: ambientum/node:9
    container_name: schedule-vue-dev
    command: npm run dev
    volumes:
      - .:/var/www/app

  build:
    image: ambientum/node:9
    container_name: schedule-vue-build
    command: npm run package-win
    volumes:
      - .:/var/www/app

  start:
    image: ambientum/node:9
    container_name: schedule-vue-start
    command: npm run start
    volumes:
      - .:/var/www/app

  # Testing dist on a "real" webserver
  production-server:
    image: nginx:stable-alpine
    container_name: schedule-preview-server
    volumes:
      - ./dist:/usr/share/nginx/html
    ports:
      - 9090:80
